services:
  financecontrol.webapi:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
  
    - JWTSETTINGS_VALIDISSUER=SERVICE_AUTHENTICATION
    - JWTSETTINGS_VALIDAUDIENCE=https://localhost
    
    - TZ=America/Fortaleza   
    
    - JWTSETTINGS_EXPIREINHOURS_WEBAPI=25
    - JTW_SECRET_KEY_SERVICE_WEBAPI=EFBDAE5A-3CE0-4178-BCEA-52A686951FDB 
    - VALIDATION_SERVICE_WEBAPI=6B341FA5-87F7-4D30-A5A9-18C9960D0E13

    - MYSQL_SERVER=mysql
    - MYSQL_PORT=3306
    - MYSQL_DB=financial
    - MYSQL_USER=financeuser
    - MYSQL_PASS=Ue7kB1ZxV9

    - MONGODB_DATABASE=FINANCE
    - MONGODB_COLLECTION_LOGS=Logs
    - MONGODB_IP=mongodb
    - MONGODB_PORT=27017
    - MONGODB_USER=mongoadmin
    - MONGODB_PASS=Tq6vF3RwH2